[project]
name = "pg-logidater"
version = "0.3.3"
description = "Postgresql logical replication setup utility"
authors = [{ name = "Arunas Grigalionis", email = "arunas.grigalionis@gmail.com" }]
requires-python = ">=3.9,<3.10"
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["postgres"]
dependencies = [
    "psycopg2-binary>=2.9.9,<3",
    "paramiko>=3.4.0,<4",
    "pycotore>=0.2.0,<0.3",
]

[project.urls]
Homepage = "https://github.com/niekosau"
Repository = "https://github.com/niekosau/pg-logidater"

[project.scripts]
pg-logidater = "pg_logidater.cli:main"

[dependency-groups]
dev = [
    "flake8>=7.0.0,<8",
    "tox>=4.14.2,<5",
    "pytest>=8.1.1,<9",
    "pytest-cov>=5.0.0,<6",
    "wheel>=0.43.0,<0.44",
    "poetry>=1.8.2,<2",
    "poetry-git-version-plugin>=1.0.8,<2",
    "twine>=5.0.0,<6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "--cov=pg-logidater"
